// Generated by Assets/Hananoki/CustomHierarchy/Editor/Localize/ja-JP.csv
namespace Hananoki.CustomHierarchy {
	public static class L {
		public static string Tr( string s ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), s );
		}
		public static string[] Tr( string[] ss ) {
			return EditorLocalize.Tr( EditorLocalize.GetPakage( Package.name ), ss );
		}
	}
	public static class S {
		public static string _Showtoggletotogglegameobjectactive => L.Tr( "Show toggle to toggle game object active" );
		public static string _Displayprefabstatuswithicons => L.Tr( "Display prefab status with icons" );
		public static string _Moveuponelevel => L.Tr( "Move up one level" );
		public static string _Pingascenefilebyclickingthesceneicon => L.Tr( "Ping a scene file by clicking the scene icon" );
		public static string _Displaytagnameandlayername => L.Tr( "Display tag name and layer name" );
	}
}
