// Generated by Assets/Hananoki/CustomHierarchy/Localize/en-US.csv

namespace Hananoki.CustomHierarchy {
	public static class L {
		public static string Tr( int n ) {
			try {
				return EditorLocalize.GetPakage( Package.name ).m_Strings[ n ];
			}
			catch( System.Exception ) {
			}
			return string.Empty;
		}
	}
	public static class S {
		public static string _Showtoggletotogglegameobjectactive => L.Tr( 0 );
		public static string _Displayprefabstatuswithicons => L.Tr( 1 );
		public static string _Moveuponelevel => L.Tr( 2 );
		public static string _Pingascenefilebyclickingthesceneicon => L.Tr( 3 );
		public static string _Displaytagnameandlayername => L.Tr( 4 );
		public static string _Displaythetree => L.Tr( 5 );
		public static string _ItemdisplayoffsetX => L.Tr( 6 );
		public static string _NumpadControl => L.Tr( 7 );
	}

#if UNITY_EDITOR
  [EditorLocalizeClass]
  public class LocalizeEvent {
    [EditorLocalizeMethod]
    public static void Changed() {
			EditorLocalize.Load( Package.name, "2eae63f13c909d54eb5e8f493fcde80b" );
		}
	}
#endif
}
